### ISSUE TITLE
Ability to update search space in response to patch evaluations

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/Darjeeling#71]
Let's say that we discover a patch at a given location, if that patch is a deletion, we should remove all other transformations at that location from the transformation space. Alternatively, we may want to update the fault localisation in response to patch results (i.e., online MBFL).

Needs to be defined as part of a search strategy.

What does mutation tell us about the shape and location of the patch? Can we combine mutation and semantics-based repair?

```
class Algorithm(object):
  def __next__(self) -> Candidate:
    ...

  def evaluated(outcome: CandidateOutcome) -> None:
    ...
```

Implement a magical setter for `Localization` that propagates its update to the transformation database.

**Comment by ChrisTimperley** [comment]
No longer necessary.

**Comment by yxliang01** [comment]
This issue is quite high-level but I think this might be required for #268 . I would think of this as an update on the filtering on the candidates, instead of "directly" update the search space. Concretely, after the (semantic) execution info is produced, it will then be used to do candidate filtering. @ChrisTimperley
